/* tslint:disable */
/* eslint-disable */
export const initialState: () => [number, number];
export const keygen: (a: number) => [number, number, number, number];
export const keypairFromSeed: (a: number, b: number, c: number) => [number, number, number, number];
export const keypairLen: () => number;
export const publicKeyFromKeypair: (a: number, b: number) => [number, number, number, number];
export const publicKeyLen: () => number;
export const secretKeyFromKeypair: (a: number, b: number) => [number, number, number, number];
export const secretKeyLen: () => number;
export const signStateful: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const signStateless: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const signatureFromStatefulSignResult: (a: number, b: number) => [number, number, number, number];
export const stateCounter: (a: number, b: number) => [number, number, number];
export const stateFromStatefulSignResult: (a: number, b: number) => [number, number, number, number];
export const stateLen: () => number;
export const statefulSignatureMaxLen: (a: number) => number;
export const statelessSignatureLen: (a: number) => number;
export const verify: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const verifyStateful: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
